TARGET := Lighthouse

TITLE := BANJO0064

TORCH_INCLUDES := Torch/src Torch/src/utils Torch/lib Torch Torch/src/factories \
	Torch/lib/n64graphics Torch/lib/binarytools

TORCH_SOURCES := Torch/src Torch/src/factories Torch/src/factories/bk64 Torch/lib/binarytools \
	Torch/src/n64 Torch/src/preprocess Torch/src/types Torch/src/utils Torch/lib/libmio0 \
	Torch/src/archive Torch/lib/binarytools Torch/lib/libyay0 Torch/lib/n64graphics \
	Torch/src/factories/naudio/v0 Torch/src/factories/naudio/v1 Torch/lib/libyaz0 \
	Torch/lib/bk_zip

LUS_INCLUDES := libultraship/include libultraship/src libultraship/src/ship/utils/binarytools libultraship/src/resource/type \
	libultraship/src/resource libultraship/src/window libultraship/src/window/gui libultraship/src/audio libultraship/src/graphic \
	libultraship/src libultraship/imgui libultraship/imgui/backends libultraship/src/public/bridge libultraship/include/libultraship \
	libultraship/src/resource/factory libultraship/imgui/backends libultraship/imgui

LUS_SOURCES := libultraship/src/fast libultraship/src/fast/resource/type libultraship/src/fast/resource/factory libultraship/src/ship/resource/factory \
	libultraship/src/fast/debug libultraship/src/fast/backends libultraship/src/ship libultraship/src/ship/audio libultraship/src/ship/resource/type \
	libultraship/src/ship/config libultraship/src/ship/controller/controldeck libultraship/src/ship/controller/controldevice libultraship/src/ship/utils \
	libultraship/src/ship/controller/controldevice/controller libultraship/src/ship/controller/controldevice/controller/mapping libultraship/src/ship/window \
	libultraship/src/ship/controller/controldevice/controller/mapping/factories libultraship/src/ship/controller/controldevice/controller/mapping/keyboard \
	libultraship/src/ship/controller/controldevice/controller/mapping/mouse libultraship/src/ship/controller/controldevice/controller/mapping/sdl \
	libultraship/src/ship/controller/physicaldevice libultraship/src/ship/debug libultraship/src/ship/resource libultraship/src/ship/resource/archive \
	libultraship/src/ship/utils/binarytools libultraship/src/ship/window/gui libultraship/src/ship/window/gui/resource libultraship/src/libultraship/window/gui \
	libultraship/src/libultraship/log libultraship/src/libultraship/libultra libultraship/src/libultraship/controller/controldeck libultraship/src/libultraship/bridge \
	libultraship/src/libultraship/controller/controldevice/controller libultraship/src/libultraship/controller/controldevice/controller/mapping libultraship/imgui \
	libultraship/src/ship/events

GAME_SOURCES := src/BGS src/BGS/ch src/boot src/CC src/CC/ch src/CC/ma src/CCW src/CCW/ch src/core1 src/core1/n_audio src/core2 src/core2/anim src/core2/ba \
	src/core2/bs src/core2/ch src/core2/collision src/core2/dialog src/core2/font src/core2/frame src/core2/fx src/core2/gc src/core2/level src/core2/map \
	src/core2/model src/core2/nc src/core2/particle src/core2/quiz src/core2/scorequeue src/core2/sfc src/core2/sprite src/core2/vtx src/cutscenes \
	src/emptylvl src/fight src/FP src/FP/ch src/FP/ma src/GV src/GV/ch src/lair src/lair/ch src/MM src/MM/ch src/MMM src/MMM/ch src/port src/port/UI \
	src/port/Save src/port/Romhack src/port/Resource src/port/Rando src/port/Patches src/port/OS src/port/ObjectExtension src/port/Network src/port/Nametag \
	src/port/Localization src/port/Interpolation src/port/GameVersion src/port/Extractor src/port/DevTools src/port/Controller src/port/Enhancements/Cheats \
	src/port/Audio src/port/Enhancements/Backports src/port/Enhancements/Camera src/port/Enhancements/Cutscenes src/port/Enhancements/Events \
	src/port/Enhancements/Fixes src/port/Enhancemenets/Gameplay src/port/Enhancements/Modes src/port/Enhancements/Restorations src/port/Enhancements/Retention \
	src/port/Enhancements/Save src/port/Enhancements/Trackers src/port/Network/Anchor src/port/Network/Anchor/Packets src/port/Rando/CheckTracker \
	src/port/Rando/CustomObject src/port/Rando/Logic src/port/Rando/Logic/Regions src/port/Rando/MiscBehavior src/port/Rando/ObjectBehavior src/port/Rando/StaticData \
	src/port/Resource/Alt src/port/Resource/Importers src/port/Resource/Type src/port/Romhack src/port/Romhack/Shared src/port/Romhack/Specific \
	src/port/UI/DeveloperTools src/RBB src/SM src/SM/ch src/TTC src/TTC/ch src/TTC/ma src/RBB/ch lib/ultralib/gu lib/ultralib/audio src/core2/sfx \
	src/port/Enhancements/Gameplay src/port/Enhancements/Cosmetics src/port/Rando/Spoiler

SOURCES := $(LUS_SOURCES) $(TORCH_SOURCES) $(GAME_SOURCES)

INCLUDES := $(LUS_INCLUDES) $(TORCH_INCLUDES) lib/ultralib/include \
	actors levels include include/PR spdlog/include include/assets include/assets/actors \
	include/assets/assets include/assets/bin include/assets/levels include/assets/textures \
	src/audio src/buffers src/engine src/game src/goddard src/menu src/pc src/port src/port/Enhancements \
	src/port/enhancements/game-interactor src/port/api textures src .

LIBS = -lstorm -lgfxd -lzip -lbzip2 -lzstd -lz -lyaml-cpp -llzma -lssl -lcrypto -lstdc++ -lpng \
	-Wl,--whole-archive -lpthread -Wl,--no-whole-archive \
	-ltinyxml2 -lSDL2 -lvorbisfile -lvorbis -logg -lvitaGL -lvitashark -lSceShaccCgExt -ltaihen_stub -lmathneon -lSceAudioIn_stub \
	-lSceIme_stub -lSceKernelDmacMgr_stub -lSceGxm_stub -lSceDisplay_stub -lSceTouch_stub -lSceHid_stub -lSceCtrl_stub -lSceNet_stub \
	-lSceNetCtl_stub -lSceCommonDialog_stub -lSceAudio_stub -lSceSysmodule_stub -lSceMotion_stub -lSceAppUtil_stub \
	-lSceAppMgr_stub -lSceShaccCg_stub -lScePower_stub -lSceNpTrophy_stub

FINAL_SOURCES := f

CFILES := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.c)) libultraship/imgui/backends/imgui_impl_opengl3.c libultraship/imgui/backends/imgui_impl_sdl2.c
CPPFILES := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.cpp))

CFILES := $(filter-out %.inc.c, $(CFILES))
CFILES := $(filter-out bin/eu/%, $(CFILES))
CFILES := $(filter-out src/game/main.c src/pc/dlmalloc.c, $(CFILES))

OBJS := $(CFILES:.c=.o) $(CPPFILES:.cpp=.o) \
	libultraship/imgui/backends/imgui_impl_opengl3.o \
	libultraship/imgui/backends/imgui_impl_sdl2.o

OBJS_PREPARE := $(CFILES:.c=.ok) $(CPPFILES:.cpp=.ok) \
	libultraship/imgui/backends/imgui_impl_opengl3.ok \
	libultraship/imgui/backends/imgui_impl_sdl2.ok

OBJS_CLEAN := $(CFILES:.c=.oc) $(CPPFILES:.cpp=.oc) \
	libultraship/imgui/backends/imgui_impl_opengl3.oc \
	libultraship/imgui/backends/imgui_impl_sdl2.oc

FINAL_OBJS := $(foreach dir,$(FINAL_SOURCES), $(wildcard $(dir)/*.o))

CVAR_PREFIX_RANDOMIZER_ENHANCEMENT := gRandoEnhancements
CVAR_PREFIX_RANDOMIZER_SETTING     := gRandoSettings
CVAR_PREFIX_COSMETIC               := gCosmetics
CVAR_PREFIX_AUDIO                  := gAudioEditor
CVAR_PREFIX_CHEAT                  := gCheats
CVAR_PREFIX_ENHANCEMENT            := gEnhancements
CVAR_PREFIX_SETTING                := gSettings
CVAR_PREFIX_WINDOW                 := gOpenWindows
CVAR_PREFIX_TRACKER                := gTrackers
CVAR_PREFIX_DEVELOPER_TOOLS        := gDeveloperTools
CVAR_PREFIX_GENERAL                := gGeneral
CVAR_PREFIX_REMOTE                 := gRemote
CVAR_PREFIX_GAMEPLAY_STATS         := gGameplayStats
CVAR_PREFIX_TIME_DISPLAY           := gTimeDisplay

PREFIX = arm-vita-eabi
CC  = $(PREFIX)-gcc
CXX = $(PREFIX)-g++

CFLAGS = -g -Wl,-q,--allow-multiple-definition -O3 -ffast-math -fno-short-enums -fsigned-char \
	$(foreach dir,$(INCLUDES),-I$(dir)) -fno-strict-aliasing \
	-Wno-narrowing -DIMGUI_IMPL_OPENGL_ES2 -DSPDLOG_ACTIVE_LEVEL=6 \
	-I$(VITASDK)/$(PREFIX)/include/SDL2 -DENABLE_OPENGL=1 -DNON_EQUIVALENT=1 \
	-D_LANGUAGE_C -D_USE_MATH_DEFINES -DCIMGUI_DEFINE_ENUMS_AND_STRUCTS -DNAUDIO_SUPPORT \
	-DAVOID_UB=1 -DN_MICRO=1 -DF3DEX_GBI=1 -DGBI_FLOATS=1 -DNON_MATCHING=1 \
	-DVERSION_US=1 -DENABLE_RUMBLE=1 -DIMGUI_DEFINE_MATH_OPERATORS -DBK64_SUPPORT \
	-DCVAR_PREFIX_RANDOMIZER_ENHANCEMENT=\"$(CVAR_PREFIX_RANDOMIZER_ENHANCEMENT)\" \
	-DCVAR_PREFIX_RANDOMIZER_SETTING=\"$(CVAR_PREFIX_RANDOMIZER_SETTING)\" \
	-DCVAR_PREFIX_COSMETIC=\"$(CVAR_PREFIX_COSMETIC)\" \
	-DCVAR_PREFIX_AUDIO=\"$(CVAR_PREFIX_AUDIO)\" \
	-DCVAR_PREFIX_CHEAT=\"$(CVAR_PREFIX_CHEAT)\" \
	-DCVAR_PREFIX_ENHANCEMENT=\"$(CVAR_PREFIX_ENHANCEMENT)\" \
	-DCVAR_PREFIX_SETTING=\"$(CVAR_PREFIX_SETTING)\" \
	-DCVAR_PREFIX_WINDOW=\"$(CVAR_PREFIX_WINDOW)\" \
	-DCVAR_PREFIX_TRACKER=\"$(CVAR_PREFIX_TRACKER)\" \
	-DCVAR_PREFIX_DEVELOPER_TOOLS=\"$(CVAR_PREFIX_DEVELOPER_TOOLS)\" \
	-DCVAR_PREFIX_GENERAL=\"$(CVAR_PREFIX_GENERAL)\" \
	-DCVAR_PREFIX_REMOTE=\"$(CVAR_PREFIX_REMOTE)\" \
	-DCVAR_PREFIX_GAMEPLAY_STATS=\"$(CVAR_PREFIX_GAMEPLAY_STATS)\" \
	-DCVAR_PREFIX_TIME_DISPLAY=\"$(CVAR_PREFIX_TIME_DISPLAY)\" \
	-DCVAR_VSYNC_ENABLED=\"gVsyncEnabled\" \
	-DCVAR_Z_FIGHTING_MODE=\"gZFightingMode\" \
	-DCVAR_NEW_FILE_DROPPED=\"gNewFileDropped\" \
	-DCVAR_DROPPED_FILE=\"gDroppedFile\" \
	-DCVAR_INTERNAL_RESOLUTION=\"gInternalResolution\" \
	-DCVAR_MSAA_VALUE=\"gMSAAValue\" \
	-DCVAR_SDL_WINDOWED_FULLSCREEN=\"gSdlWindowedFullscreen\" \
	-DCVAR_TEXTURE_FILTER=\"gTextureFilter\" \
	-DCVAR_IMGUI_CONTROLLER_NAV=\"gControlNav\" \
	-DCVAR_CONSOLE_WINDOW_OPEN=\"gConsoleEnabled\" \
	-DCVAR_CONTROLLER_CONFIGURATION_WINDOW_OPEN=\"gControllerConfigurationEnabled\" \
	-DCVAR_CONTROLLER_DISCONNECTED_WINDOW_OPEN=\"gControllerDisconnectedWindowEnabled\" \
	-DCVAR_CONTROLLER_REORDERING_WINDOW_OPEN=\"gControllerReorderingWindowEnabled\" \
	-DCVAR_GFX_DEBUGGER_WINDOW_OPEN=\"gGfxDebuggerEnabled\" \
	-DCVAR_STATS_WINDOW_OPEN=\"gStatsEnabled\" \
	-DCVAR_ENABLE_MULTI_VIEWPORTS=\"gEnableMultiViewports\" \
	-DCVAR_LOW_RES_MODE=\"gLowResMode\" \
	-DCVAR_SIMULATED_INPUT_LAG=\"gSimulatedInputLag\" \
	-DCVAR_GAME_OVERLAY_FONT=\"gOverlayFont\" \
	-DCVAR_MENU_BAR_OPEN=\"gOpenMenuBar\" \
	-DCVAR_PREFIX_CONTROLLERS=\"gControllers\" \
	-DCVAR_PREFIX_ADVANCED_RESOLUTION=\"gAdvancedResolution\" \
	-DCVAR_AUDIO_CHANNELS_SETTING=\"gAudioChannelsSetting\" \
	-DCVAR_ALLOW_BACKGROUND_INPUTS=\"gAllowBackgroundInputs\" \
	-DCVAR_SCRIPT_SAFE_LEVEL=\"gScriptSafeLevel\"

CXXFLAGS = $(CFLAGS) -fexceptions -std=gnu++20 -fpermissive
ASFLAGS  = $(CFLAGS)

all: $(TARGET).vpk

$(TARGET).vpk: $(TARGET).velf
	vita-make-fself -c -s $< eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLE) -d ATTRIBUTE2=12 "$(TARGET)" param.sfo
	vita-pack-vpk -s param.sfo -b eboot.bin $(TARGET).vpk \
		-a livearea/icon0.png=sce_sys/icon0.png \
		-a livearea/bg.png=sce_sys/livearea/contents/bg.png \
		-a livearea/startup.png=sce_sys/livearea/contents/startup.png \
		-a livearea/template.xml=sce_sys/livearea/contents/template.xml

prepare: f $(OBJS_PREPARE)

f:
	mkdir f

%.ok:
	$(eval gen_num=$(shell echo $$(($(gen_num)+1))))
	@cp $(@:k=) f/$(gen_num).o

%.oc:
	@rm -rf $(@:c=)

%.velf: %.elf
	cp $< $<.unstripped.elf
	$(PREFIX)-strip -g $<
	vita-elf-create $< $@

$(TARGET).elf: $(FINAL_OBJS)
	$(CXX) $(CXXFLAGS) $^ $(LIBS) -o $@

objects: $(OBJS)

clean: $(OBJS_CLEAN)
	@rm -rf $(TARGET).velf $(TARGET).elf $(FINAL_OBJS) eboot.bin $(TARGET).vpk param.sfo